<a href="https://colab.research.google.com/github/surekhavydyula4-cmd/ML/blob/main/train_test_slpit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Creating an array
from sklearn.model_selection import train_test_split
import numpy as np

#Numpy array
data=np.arange(10)

print(data)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
# Creating an array
from sklearn.model_selection import train_test_split
import numpy as np

#Numpy array
data=np.arange(10)

#Splitting the data
data_split=train_test_split(data)

print(data)
print()
print(data_split)

[0 1 2 3 4 5 6 7 8 9]

[array([1, 5, 3, 6, 9, 8, 2]), array([4, 7, 0])]


In [5]:
# Creating an array
from sklearn.model_selection import train_test_split
import numpy as np

#Numpy array
data=np.arange(10)

#Splitting the data
data_split=train_test_split(data,train_size=6)

print(data)
print()
print(data_split)

[0 1 2 3 4 5 6 7 8 9]

[array([3, 7, 5, 4, 6, 9]), array([1, 0, 8, 2])]


In [7]:
# Creating an array
from sklearn.model_selection import train_test_split
import numpy as np

#Numpy array
data=np.arange(10)

#Splitting the data
train,test=train_test_split(data)

print(data)
print()
print(train)
print()
print(test)

[0 1 2 3 4 5 6 7 8 9]

[2 9 0 5 8 3 4]

[6 7 1]


In [8]:
# Creating an array
from sklearn.model_selection import train_test_split
import numpy as np

#Numpy array
data=np.arange(10)

#Splitting the data
train,test=train_test_split(data,test_size=4)

print(data)
print()
print(train)
print()
print(test)

[0 1 2 3 4 5 6 7 8 9]

[0 4 6 2 1 3]

[8 5 7 9]


In [10]:
# Creating an array
from sklearn.model_selection import train_test_split
import numpy as np

#Numpy array
data=np.arange(10)

#Splitting the data
train,test=train_test_split(data,train_size=0.6)

print(data)
print()
print(train)
print()
print(test)

[0 1 2 3 4 5 6 7 8 9]

[8 5 0 6 4 1]

[7 3 2 9]


In [ ]:
# Creating an array
from sklearn.model_selection import train_test_split
import numpy as np

#Numpy array
data=np.arange(10)

#Splitting the data
train,test=train_test_split(data,train_size=0.4)

print(data)
print()
print(train)
print()
print(test)

In [11]:
# Creating an array
from sklearn.model_selection import train_test_split
import numpy as np

#Numpy array
data=np.arange(10)

#Splitting the data
train,test=train_test_split(data,train_size=4,test_size=4)

print(data)
print()
print(train)
print()
print(test)

[0 1 2 3 4 5 6 7 8 9]

[2 5 7 9]

[0 6 4 1]


In [12]:
# Creating an array
from sklearn.model_selection import train_test_split
import numpy as np

#Numpy array
data=np.arange(10)

#Splitting the data
train,test=train_test_split(data,train_size=4,test_size=6)

print(data)
print()
print(train)
print()
print(test)

[0 1 2 3 4 5 6 7 8 9]

[8 3 4 7]

[1 9 0 5 2 6]


In [13]:
#Error
# Importing libraries
from sklearn.model_selection import train_test_split
import numpy as np

#Numpy array
data=np.arange(10)

#Splitting the data
train,test=train_test_split(data,train_size=4,test_size=10)

print(data)
print()
print(train)
print()
print(test)

ValueError: test_size=10 should be either positive and smaller than the number of samples 10 or a float in the (0, 1) range

In [16]:
#random state
#Importing libraries
from sklearn.model_selection import train_test_split
import numpy as np

#data
data=np.arange(10)

#Splitting the data
train,test=train_test_split(data,random_state=0)

print(data)
print()
print(train)
print()
print(test)

[0 1 2 3 4 5 6 7 8 9]

[9 1 6 7 3 0 5]

[2 8 4]


In [18]:
#random state
#Importing libraries
from sklearn.model_selection import train_test_split
import numpy as np

#data
data=np.arange(10)

#Splitting the data
train,test=train_test_split(data,train_size=4,test_size=4,random_state=0)

print(data)
print()
print(train)
print()
print(test)

[0 1 2 3 4 5 6 7 8 9]

[1 6 7 3]

[2 8 4 9]
